swagger: '2.0'
info:
  title: Logistics Wizard Recommendation API
  description: The recommendation service of logistic wizard, interfacing with the controlling services.
  version: "1.0.0"
# the domain of the service
host: 
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
